CREATE SCHEMA IF NOT EXISTS PUBLIC;

CREATE TABLE IF NOT EXISTS RAW_EVENTS (
	ID VARCHAR(256),
	STATE VARCHAR(10),
	TYPE VARCHAR(20),
	HOST VARCHAR(10),
	TIMESTAMP BIGINT,
	PRIMARY KEY (ID, STATE)
)

CREATE TABLE IF NOT EXISTS EVENTS (
	ID VARCHAR(256),
	DURATION INTEGER,
	TYPE VARCHAR(20),
	HOST VARCHAR(10),
	ALERT BOOLEAN,
	PRIMARY KEY (ID)
)

SET SCHEMA PUBLIC;